### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by DerGroncki** [gotham-rs/example-app#3]
Are you supporting Windows?

Because I get the following errors:

 Compiling gotham v0.1.0
error[E0432]: unresolved import `std::os::unix::net::UnixStream`
 --> C:\Users\micha\.cargo\registry\src\github.com-1ecc6299db9ec823\gotham-0.1.0\src\test\mod.rs:9:5
  |
9 | use std::os::unix::net::UnixStream;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `unix` in `os`

Thank you.

Michael

**Comment by smangelsdorf** [comment]
Thanks for raising this. We've got an active PR to fix Windows support in Gotham itself, after which it'll be supported here in the example app:
https://github.com/gotham-rs/gotham/pull/30

**Comment by DerGroncki** [comment]
Ok, thank you. Looking forward to check out Gotham.

Michael

**Comment by smangelsdorf** [comment]
This is fixed with the release of Gotham 0.1.1 today. `cargo update` to update the Gotham version in your cloned repo, and you'll be able to run it.
